apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: opendatahub
  labels:
    app: slack-mcp
type: Opaque
stringData:
  SLACK_MCP_XOXP_TOKEN: token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slack-mcp
  name: slack-mcp
  namespace: opendatahub
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: slack-mcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack-mcp
    spec:
      containers:
        - name: slack-mcp
          image: quay.io/anastas/slack-mcp-server:latest
          imagePullPolicy: Always
          env:
            - name: MCP_TRANSPORT
              value: "sse"
            - name: FASTMCP_HOST
              value: "0.0.0.0"
            - name: SLACK_MCP_ADD_MESSAGE_TOOL
              value: "true"
            - name: LOGS_CHANNEL_ID
              value: "C0700000000"
            - name: LOGS_CHANNEL_ID
              value: "C0700000000"
            - name: SLACK_MCP_XOXP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-credentials
                  key: SLACK_MCP_XOXP_TOKEN
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: slack-mcp
  labels:
    app: slack-mcp
  namespace: opendatahub
spec:
  selector:
    app: slack-mcp
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP